language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - cd web
  - echo $PWD
script:
  - npm install
  - npm test
  - npm run build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $github_token
#   local_dir: build
#   on:
#     branch: master
